/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';

import {
  RouterHistory,
} from '@stencil/router';

declare global {

  namespace StencilComponents {
    interface LoginComponent {
      'history': RouterHistory;
    }
  }

  interface HTMLLoginComponentElement extends StencilComponents.LoginComponent, HTMLStencilElement {}

  var HTMLLoginComponentElement: {
    prototype: HTMLLoginComponentElement;
    new (): HTMLLoginComponentElement;
  };
  interface HTMLElementTagNameMap {
    'login-component': HTMLLoginComponentElement;
  }
  interface ElementTagNameMap {
    'login-component': HTMLLoginComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'login-component': JSXElements.LoginComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface LoginComponentAttributes extends HTMLAttributes {
      'history'?: RouterHistory;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface RouterComponent {

    }
  }

  interface HTMLRouterComponentElement extends StencilComponents.RouterComponent, HTMLStencilElement {}

  var HTMLRouterComponentElement: {
    prototype: HTMLRouterComponentElement;
    new (): HTMLRouterComponentElement;
  };
  interface HTMLElementTagNameMap {
    'router-component': HTMLRouterComponentElement;
  }
  interface ElementTagNameMap {
    'router-component': HTMLRouterComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'router-component': JSXElements.RouterComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface RouterComponentAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface TilesComponent {
      'first': string;
      'history': RouterHistory;
      'last': string;
    }
  }

  interface HTMLTilesComponentElement extends StencilComponents.TilesComponent, HTMLStencilElement {}

  var HTMLTilesComponentElement: {
    prototype: HTMLTilesComponentElement;
    new (): HTMLTilesComponentElement;
  };
  interface HTMLElementTagNameMap {
    'tiles-component': HTMLTilesComponentElement;
  }
  interface ElementTagNameMap {
    'tiles-component': HTMLTilesComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'tiles-component': JSXElements.TilesComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface TilesComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'history'?: RouterHistory;
      'last'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
